name: endpoint
description: "Death at Sunrise"

version: 0.43.3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  showcaseview: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - pubspec.yaml
    - assets/images/
    - assets/images/icons/
    - assets/images/slots/
    - assets/images/tiles/
    - assets/sprites/
    - assets/sprites/items/
    - assets/sprites/monsters/
  fonts:
    - family: Pixeboy
      fonts:
        - asset: fonts/Pixeboy-z8XGD.ttf
    - family: Rajdhani
      fonts:
        - asset: fonts/Rajdhani-Regular.ttf
    - family: Exo2
      fonts:
        - asset: fonts/Exo2-VariableFont_wght.ttf

